import { Platform, StyleSheet } from 'react-native';

export const colors = {
  background: '#FFF8F0',
  primary: '#FFAE2B',
  primaryDark: '#F59B00',
  heading: '#1F1F1F',
  body: '#777777',
  muted: '#969696',
  border: '#E5E5E5',
  white: '#FFFFFF',
  disabled: '#F4F4F4',
  priceBubble: '#FFF0D4',
};

export const fonts = {
  heading: 'Sora-SemiBold',
  subHeading: 'Sora-Medium',
  body: 'WorkSans-Medium',
  regular: 'WorkSans-Regular',
};

export const sharedShadow = {
  shadowColor: '#000000',
  shadowOpacity: 0.08,
  shadowRadius: 12,
  shadowOffset: { width: 0, height: 5 },
  elevation: 3,
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  root: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    paddingBottom: 124,
  },
  tabletContent: {
    alignSelf: 'center',
    maxWidth: 700,
    width: '100%',
  },
  heroWrap: {
    backgroundColor: colors.background,
  },
  heroImageWrap: {
    width: '100%',
    // height: 500,
    aspectRatio: 0.96,
    overflow: 'hidden',
    backgroundColor: '#F3EEE8',
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  heroOverlay: {
    ...StyleSheet.absoluteFill,
  },
  backButton: {
    position: 'absolute',
    left: 30,
    top: 50,
    width: 30,
    height: 30,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(145,145,145,0.48)',
  },
  curveSvg: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: -1,
  },
  serviceCard: {
    position: 'absolute',
    left: 42,
    right: 42,
    bottom: -22,
    // minHeight: 102,
    borderRadius: 18,
    backgroundColor: colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 18,
    ...sharedShadow,
  },
  serviceTitle: {
    fontFamily: fonts.heading,
    fontSize: 16,
    color: colors.heading,
  },
  durationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 14,
  },
  clockCircle: {
    width: 18,
    height: 18,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.muted,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 9,
  },
  durationText: {
    fontFamily: fonts.regular,
    fontSize: 16,
    color: colors.muted,
  },
  priceLabel: {
    fontFamily: fonts.regular,
    fontSize: 12,
    color: colors.muted,
    textTransform: 'uppercase',
  },
  priceValue: {
    marginTop: 22,
    textAlign: 'right',
    fontFamily: fonts.heading,
    fontSize: 16,
    color: colors.heading,
  },
  section: {
    paddingHorizontal: 21,
  },
  firstSection: {
    paddingTop: 40,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 21,
  },
  sectionTitle: {
    fontFamily: fonts.heading,
    fontSize: 16,
    color: colors.heading,
  },
  sectionSideText: {
    fontFamily: fonts.regular,
    fontSize: 14,
    color: colors.muted,
  },
  guestRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  guestButton: {
    height: 35,
    borderRadius: 28,
    borderWidth: 1.5,
    borderColor: colors.muted,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  guestButtonSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  guestText: {
    fontFamily: fonts.body,
    fontSize: 18,
    color: colors.heading,
  },
  guestTextSelected: {
    color: colors.white,
  },
  scheduleSection: {
    paddingTop: 20,
  },
  nextAvailable: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  nextAvailableText: {
    fontFamily: fonts.body,
    fontSize: 12,
    color: colors.primary,
    marginLeft: 5,
    textTransform: 'uppercase',
  },
  tabsCard: {
    height: 60,
    borderRadius: 16,
    backgroundColor: colors.white,
    flexDirection: 'row',
    overflow: 'hidden',
  },
  dateTab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateTabText: {
    fontFamily: fonts.body,
    fontSize: 14,
    color: colors.muted,
  },
  dateTabTextActive: {
    color: colors.heading,
  },
  dateUnderline: {
    position: 'absolute',
    bottom: 16,
    width: '70%',
    height: 3,
    borderRadius: 2,
    backgroundColor: colors.primary,
  },
  slotCard: {
    marginTop: 10,
    borderRadius: 16,
    backgroundColor: colors.white,
    padding: 10,
  },
  slotGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  slotButton: {
    height: 40,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.white,
    marginBottom: 18,
  },
  slotButtonSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    ...sharedShadow,
  },
  slotButtonDisabled: {
    backgroundColor: colors.disabled,
    borderColor: colors.border,
  },
  slotText: {
    fontFamily: fonts.body,
    fontSize: 14,
    color: colors.muted,
  },
  slotTextSelected: {
    color: colors.white,
  },
  slotTextDisabled: {
    color: '#D3D3D3',
  },
  selectedBadge: {
    position: 'absolute',
    right: 2,
    top: 2,
    backgroundColor: colors.heading,
    borderRadius: 2,
    paddingHorizontal: 3,
    paddingVertical: 2,
  },
  selectedBadgeText: {
    fontFamily: fonts.body,
    fontSize: 7,
    color: colors.white,
  },
  optionSection: {
    paddingTop: 34,
  },
  optionCard: {
    // minHeight: 134,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
    paddingHorizontal: 15,
    paddingVertical: 15,
    overflow: 'hidden',
  },
  optionTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 14,
    borderWidth: 3,
    borderColor: colors.heading,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 17,
    marginTop: 2,
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 7,
    backgroundColor: colors.heading,
  },
  optionCopy: {
    flex: 1,
    paddingRight: 84,
  },
  optionTitle: {
    fontFamily: fonts.heading,
    fontSize: 16,
    color: colors.heading,
  },
  optionSubtitle: {
    marginTop: 4,
    fontFamily: fonts.regular,
    fontSize: 11,
    color: colors.muted,
  },
  optionDescription: {
    marginTop: 10,
    fontFamily: fonts.regular,
    fontSize: 11,
    // lineHeight: 22,
    color: colors.muted,
  },
  priceBubble: {
    position: 'absolute',
    right: -20,
    top: 0,
    width: 100,
    height: 70,
    borderBottomLeftRadius: 70,
    backgroundColor: colors.priceBubble,
    alignItems: 'center',
    justifyContent: 'center',
    paddingRight: 18,
    paddingTop: 10,
  },
  priceBubbleText: {
    fontFamily: fonts.heading,
    fontSize: 16,
    color: colors.heading,
  },
  footerWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.background,
    paddingHorizontal: 21,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(229,229,229,0.4)',
  },
  footerInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  payLabel: {
    fontFamily: fonts.regular,
    fontSize: 14,
    color: colors.muted,
  },
  payValue: {
    marginTop: 4,
    fontFamily: fonts.heading,
    fontSize: 18,
    color: colors.heading,
  },
  proceedButton: {
    minWidth: '52%',
    height: 50,
    borderRadius: 16,
    overflow: 'hidden',
  },
  proceedGradient: {
    flex: 1,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  proceedPressed: {
    opacity: Platform.OS === 'ios' ? 0.7 : 0.85,
  },
  proceedText: {
    fontFamily: fonts.heading,
    fontSize: 18,
    color: colors.white,
  },
});
