export const CrashlyticsErrors = {
  API_ERROR: 'API_ERROR',

  PAYMENT_ERROR: 'PAYMENT_ERROR',

  BOOKING_ERROR: 'BOOKING_ERROR',

  AUTH_ERROR: 'AUTH_ERROR',

  LOCATION_ERROR: 'LOCATION_ERROR',

  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;