import { StyleSheet } from 'react-native';

export const colors = {
  background: '#FFF8F1',
  primary: '#FFAE2B',
  primaryDark: '#F59C00',
  primaryLight: '#FFD56A',
  heading: '#1E1E1E',
  body: '#6D6D6D',
  muted: '#9D9D9D',
  border: '#EFE6DA',
  white: '#FFFFFF',
  logout: '#FF3B30',
};


export const fonts = {
  heading: 'Sora-SemiBold',
  subHeading: 'Sora-Medium',
  body: 'WorkSans-Medium',
  regular: 'WorkSans-Regular',
};

export const shadow = {
  shadowColor: '#000000',
  shadowOpacity: 0.07,
  shadowRadius: 13,
  shadowOffset: { width: 0, height: 7 },
  elevation: 3,
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  root: {
    flex: 1,
    backgroundColor: colors.background,
  },
  loadingProfileBlock: {
    minHeight: 220,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollContent: {
    paddingBottom: 116,
  },
  tabletContent: {
    alignSelf: 'center',
    maxWidth: 600,
    width: '100%',
  },
  headerGradient: {
    ...StyleSheet.absoluteFill,
  },
  headerCircleLarge: {
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    right: -60,
    top: -100,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
  },
  headerCircleSoft: {
    position: 'absolute',
    width: 36,
    height: 36,
    borderRadius: 18,
    left: '42%',
    top: 36,
    backgroundColor: 'rgba(245, 156, 0, 0.2)',
  },
  headerDotOne: {
    position: 'absolute',
    width: 22,
    height: 22,
    borderRadius: 11,
    left: 48,
    bottom: 48,
    backgroundColor: 'rgba(245, 156, 0, 0.25)',
  },
  headerDotTwo: {
    position: 'absolute',
    width: 14,
    height: 14,
    borderRadius: 7,
    right: 64,
    bottom: 56,
    backgroundColor: 'rgba(197, 192, 182, 0.35)',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    minHeight: 44,
  },
  header: {
    // minHeight: 246,
    backgroundColor: colors.primary,
    overflow: 'hidden',
    paddingHorizontal: 28,
    paddingBottom: 50,
    justifyContent: 'center',
  },
  // headerCircleLarge: {
  //   position: 'absolute',
  //   width: 330,
  //   height: 330,
  //   borderRadius: 165,
  //   right: -20,
  //   top: -118,
  //   backgroundColor: 'rgba(255,255,255,0.12)',
  // },
  // headerCircleSoft: {
  //   position: 'absolute',
  //   width: 40,
  //   height: 40,
  //   borderRadius: 39,
  //   left: '37%',
  //   top: 46,
  //   backgroundColor: 'rgba(245,156,0,0.12)',
  // },
  // headerDotOne: {
  //   position: 'absolute',
  //   width: 28,
  //   height: 28,
  //   borderRadius: 14,
  //   right: 78,
  //   top: 42,
  //   backgroundColor: 'rgba(245,156,0,0.14)',
  // },
  // headerDotTwo: {
  //   position: 'absolute',
  //   width: 26,
  //   height: 26,
  //   borderRadius: 13,
  //   left: 112,
  //   bottom: 28,
  //   backgroundColor: 'rgba(245,156,0,0.18)',
  // },
  headerDotDark: {
    position: 'absolute',
    width: 36,
    height: 36,
    borderRadius: 18,
    right: '38%',
    bottom: 48,
    backgroundColor: 'rgba(117,83,5,0.35)',
  },
  headerTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontFamily: fonts.heading,
    fontSize: 16,
    color: colors.white,
  },
  notificationButton: {
    width: 35,
    height: 35,
    borderRadius: 31,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadow,
  },
  userCard: {
    marginHorizontal: 0,
    marginTop: -38,
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 15,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: colors.background
  },
  userCardInner: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarWrap: {
    width: 100,
    height: 100,
    borderRadius: 71,
    borderWidth: 4,
    borderColor: colors.white,
    backgroundColor: '#ECECEC',
    ...shadow,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 67,
  },
  editButton: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 30,
    height: 30,
    borderRadius: 19,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadow,
  },
  userMeta: {
    flex: 1,
    marginLeft: 34,
  },
  userName: {
    fontFamily: fonts.heading,
    fontSize: 18,
    color: colors.heading,
    marginBottom: 10,
  },
  userEmail: {
    fontFamily: fonts.regular,
    fontSize: 14,
    color: colors.body,
    marginBottom: 10,
  },
  userPhone: {
    fontFamily: fonts.regular,
    fontSize: 14,
    color: colors.body,
  },
  compactUserCard: {
    paddingHorizontal: 20,
  },
  compactAvatar: {
    width: 100,
    height: 100,
    borderRadius: 56,
  },
  compactAvatarImage: {
    borderRadius: 52,
  },
  compactMeta: {
    marginLeft: 22,
  },
  supportRow: {
    flexDirection: 'row',
    gap: 14,
    paddingHorizontal: 15,
    marginTop: 0,
  },
  supportCard: {
    flex: 1,
    minHeight: 70,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#FFD99C',
    backgroundColor: colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  supportIconCircle: {
    width: 35,
    height: 35,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
    marginRight: 12,
  },
  supportEyebrow: {
    fontFamily: fonts.regular,
    fontSize: 10,
    color: colors.primary,
    marginBottom: 6,
  },
  supportTitle: {
    fontFamily: fonts.body,
    fontSize: 12,
    color: colors.heading,
  },
  menuCard: {
    marginTop: 20,
    marginHorizontal: 20,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: colors.white,
  },
  menuItem: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 22,
  },
  menuIconWrap: {
    width: 25,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 18,
  },
  menuLabel: {
    flex: 1,
    fontFamily: fonts.regular,
    fontSize: 14,
    color: colors.muted,
  },
  menuLabelDestructive: {
    color: colors.logout,
  },
  menuDivider: {
    height: 1,
    backgroundColor: '#F3ECE3',
    marginLeft: 54,
  },
  versionWrap: {
    alignItems: 'center',
    paddingTop: 20,
    paddingBottom: 12,
  },
  appName: {
    fontFamily: fonts.body,
    fontSize: 14,
    color: colors.primary,
    marginBottom: 5,
  },
  appVersion: {
    fontFamily: fonts.regular,
    fontSize: 12,
    color: colors.muted,
  },
});
