import { Platform, StyleSheet } from 'react-native';
import { COLORS, FONTS } from './constants';

export const shadow = {
  shadowColor: '#000000',
  shadowOpacity: 0.05,
  shadowRadius: 12,
  shadowOffset: { width: 0, height: 6 },
  elevation: 2,
};

export const colors = {
  background: '#FFF8F1',
  card: '#FFFFFF',
  primary: '#FFAE2B',
  primaryDark: '#F59C00',
  primaryLight: '#FFD56A',
  heading: '#1E1E1E',
  body: '#6D6D6D',
  white: '#FFFFFF',
  link: '#FFAE2B',
  backBtnBg: 'rgba(0, 0, 0, 0.18)',
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  keyboardView: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  screenRoot: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContent: {
    paddingBottom: 45,
  },
  tabletContent: {
    alignSelf: 'center',
    maxWidth: 600,
    width: '100%',
  },
  header: {
    minHeight: 165,
    backgroundColor: COLORS.primary,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingBottom: 48,
  },
  backButton: {
      position: 'absolute',
      left: 16,
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.backBtnBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    backButtonPressed: {
      opacity: Platform.OS === 'ios' ? 0.7 : 1,
    },
  headerCircleLarge: {
    position: 'absolute',
    width: 330,
    height: 330,
    borderRadius: 165,
    right: 96,
    top: -120,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  headerCircleSoft: {
    position: 'absolute',
    width: 55,
    height: 55,
    borderRadius: 28,
    left: '34%',
    top: 39,
    backgroundColor: 'rgba(245,156,0,0.13)',
  },
  headerDotLeft: {
    position: 'absolute',
    width: 24,
    height: 24,
    borderRadius: 12,
    left: '23%',
    bottom: 75,
    backgroundColor: 'rgba(245,156,0,0.16)',
  },
  headerDotRight: {
    position: 'absolute',
    width: 22,
    height: 22,
    borderRadius: 11,
    right: 30,
    top: 98,
    backgroundColor: 'rgba(245,156,0,0.18)',
  },
  headerDotDark: {
    position: 'absolute',
    width: 33,
    height: 33,
    borderRadius: 17,
    right: '39%',
    bottom: 96,
    backgroundColor: 'rgba(117,83,5,0.32)',
  },
  headerTitle: {
    fontFamily: FONTS.heading,
    fontSize: 18,
    color: COLORS.white,
    textAlign: 'center',
  },
  headerSubtitle: {
    marginTop: 5,
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: COLORS.white,
    textAlign: 'center',
  },
  contentCard: {
    marginTop: -30,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: COLORS.background,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  photoCard: {
    minHeight: 152,
    borderRadius: 20,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    paddingHorizontal: 20,
    ...shadow,
  },
  uploadCircle: {
    width: 40,
    height: 40,
    borderRadius: 35,
    backgroundColor: COLORS.background,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
    overflow: 'hidden',
  },
  selectedPhoto: {
    width: '100%',
    height: '100%',
  },
  photoTitle: {
    fontFamily: FONTS.heading,
    fontSize: 14,
    color: COLORS.heading,
  },
  photoSubtitle: {
    marginTop: 8,
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: COLORS.placeholder,
  },
  chooseButton: {
    marginTop: 15,
    minWidth: 108,
    minHeight: 40,
    borderRadius: 23,
    borderWidth: 1.5,
    borderColor: COLORS.body,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  chooseButtonText: {
    fontFamily: FONTS.body,
    fontSize: 14,
    color: COLORS.primary,
  },
  row: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 15,
  },
  rowItem: {
    flex: 1,
  },
  inputShell: {
    minHeight: 68,
    borderRadius: 14,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 13,
    ...shadow,
  },
  inputDisabled: {
    backgroundColor: COLORS.white,
    opacity: 0.92,
  },
  inputLabel: {
    fontFamily: FONTS.body,
    fontSize: 12,
    color: COLORS.placeholder,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  inputText: {
    flex: 1,
    fontFamily: FONTS.body,
    fontSize: 14,
    color: COLORS.heading,
    padding: 0,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  blockSpacing: {
    marginTop: 20,
  },
  errorText: {
    marginTop: 6,
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: '#FF3B30',
  },
  phoneCode: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 16,
  },
  phoneCodeText: {
    fontFamily: FONTS.body,
    fontSize: 14,
    color: COLORS.heading,
    marginRight: 8,
  },
  phoneDivider: {
    width: 1,
    height: 24,
    backgroundColor: COLORS.border,
    marginRight: 16,
  },
  genderCard: {
    minHeight: 80,
    borderRadius: 14,
    backgroundColor: COLORS.white,
    paddingHorizontal: 18,
    paddingVertical: 16,
    ...shadow,
  },
  genderRow: {
    flexDirection: 'row',
    gap: 14,
  },
  genderButton: {
    flex: 1,
    minHeight: 45,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  genderButtonSelected: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  genderText: {
    fontFamily: FONTS.body,
    fontSize: 14,
    color: COLORS.heading,
    marginLeft: 6,
  },
  genderTextSelected: {
    color: COLORS.white,
  },
  dateButton: {
    minHeight: 68,
    borderRadius: 14,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 13,
    ...shadow,
  },
  dateContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dateValue: {
    flex: 1,
    fontFamily: FONTS.body,
    fontSize: 14,
    color: COLORS.heading,
  },
  addressCard: {
    minHeight: 100,
    borderRadius: 14,
    backgroundColor: COLORS.white,
    paddingHorizontal: 18,
    paddingVertical: 17,
    ...shadow,
  },
  addressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  editAddressButton: {
    minHeight: 35,
    borderRadius: 18,
    backgroundColor: COLORS.background,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  editAddressText: {
    marginLeft: 6,
    fontFamily: FONTS.body,
    fontSize: 12,
    color: COLORS.primary,
  },
  addressLineOne: {
    fontFamily: FONTS.body,
    fontSize: 14,
    color: COLORS.heading,
    marginBottom: 10,
  },
  addressLineTwo: {
    fontFamily: FONTS.regular,
    fontSize: 14,
    color: COLORS.placeholder,
  },
  saveWrap: {
    paddingHorizontal: 25,
    paddingTop: 20,
  },
  saveButton: {
    minHeight: 45,
    borderRadius: 16,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  saveButtonPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.99 }],
  },
  saveButtonDisabled: {
    opacity: 0.7,
  },
  saveButtonText: {
    fontFamily: FONTS.heading,
    fontSize: 18,
    color: COLORS.white,
  },
  placesContainer: {
    position: 'absolute',
    left: 20,
    right: 20,
    top: 110,
    zIndex: 50,
    borderRadius: 14,
    backgroundColor: COLORS.white,
    overflow: 'hidden',
    ...shadow,
    elevation: 20,
  },
  placesTextInput: {
    minHeight: 54,
    fontFamily: FONTS.body,
    fontSize: 14,
    color: COLORS.heading,
    backgroundColor: COLORS.white,
  },
  placesListView: {
    backgroundColor: COLORS.white,
    maxHeight: 320,
    zIndex: 51,
    elevation: 21,
  },
  placesRow: {
    backgroundColor: COLORS.white,
    paddingVertical: 14,
  },
  placesDescription: {
    fontFamily: FONTS.regular,
    fontSize: 12,
    color: COLORS.body,
  },
  placesOverlayBackdrop: {
    ...StyleSheet.absoluteFill,
    zIndex: 40,
    backgroundColor: 'rgba(0,0,0,0.08)',
  },
});
